I- Despacho de D por la mañana
D-¿Qué papeles son estos?
JD-Lo que se va a tratar con Vladi 
D-¿Tenemos confirmación de los asistentes?
JD-Casí, casi
D-¿Has llamado a ese?
JD- ¿A quién a Vladi?
D-No a Vladi le llamaré yo. Al pedigüeño.
JD-Si y dice que bien, que irá si le invitáis. Parece que anda falto de material. Se queja de Vladi tiene de todo y que así no hay quién le gane. Me ha pedido, casi rogado, que le demos muchos y de los gordos. Lo que no sabe es el precio. Cree que será todo como antes.
D- Si, como con el demenciado, todo de regaliz. Le habrás dicho que de eso nada
JD-Claro, claro, le he dicho que se los daremos pero que le saldrán caros.
D-Bien, has hecho algo muy importante. ¿Hay algo más?
JD- Hambre en el mundo, guerras regionales, asesinatos ...
D- Tu eres bobo. Algo que interese a América, algo nos interese, que me interese a mí. 
JD- Si, por fin Petro se ha callado.
D-Ese terrorista, mejor se calla o le.... ¡Este no estará invitado a lo del pedigüeño!
JD-No pinta nada allí. Mejor se queda en su casa.
D- Además si van muchos no hay quien entienda nada. Yo, si pudiese, no iría
JD-Pues no vaya
D-Tengo ganas de ver a Vladi y darle un abrazo
JD- Eso de momento. ¿No?
